apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: lnpo994na-nodejs 
  janus-idp.io/tekton: lnpo994na-nodejs
  backstage.io/kubernetes-id: lnpo994na-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: lnpo994na-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  